site:
    title: 生活∙编码日记
    subtitle: keep it simple and stupid.
    logo: -/images/tizzybec.jpg
    limit: 10
    theme: theme
    disqus: tizzybec
    lang: zh
    url: http://tizzybec.github.io/
    # root: /blog

authors:
    me:
        name: tizzybec
        intro: c++码农，haskell/clojure学习中...
        avatar: -/images/tizzybec.jpg

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        from_oath=~/Github/go/src/github.com/tizzybec/ink/template/public/
        to_path=~/Github/tizzybec.github.io
        cp -RP $from_oath $to_path
        cd $to_path
        git add . -A
        git commit -m "update"
        git push origin
