site:
    title: tizzybec@weibo
    subtitle: 但行好事，莫问前程.
    logo: -/images/tizzybec.jpg
    limit: 10
    theme: theme
    disqus: tizzybec
    lang: zh
    url: http://www.tizzybec.com/
    # root: /blog

authors:
    me:
        name: tizzybec
        intro: c++程序员，haskell/luajit学习中...
        avatar: -/images/tizzybec.jpg

build:
    port: 8000
    # Copied files to public folder when build
    copy:
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    # Excuted command when use 'ink publish'
    publish: |
        export from_path=~/Github/go/src/github.com/tizzybec/ink/template/public/
        export to_path=~/Github/tizzybec.github.io/
        cp -RP $from_path $to_path
        cd $to_path
        git add . -A
        git commit -m "update"
        git push origin
